const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 100,
    favorite: false,
    origins: ["Italy", "US"],
    stars: 4.5,
    imageUrl: "food-10.jpg",
    tags: ["Fast Food", "Pizza"],
  },
  {
    id: "2",
    name: "Cheeseburger",
    cookTime: "5-15",
    price: 80,
    favorite: true,
    origins: ["US"],
    stars: 4.0,
    imageUrl: "food-2.jpg",
    tags: ["Fast Food", "Burger"],
  },
  {
    id: "3",
    name: "Sushi",
    cookTime: "20-30",
    price: 150,
    favorite: false,
    origins: ["Japan"],
    stars: 4.7,
    imageUrl: "food-3.jpg",
    tags: ["Healthy", "Seafood"],
  },
  {
    id: "4",
    name: "Tacos",
    cookTime: "10-15",
    price: 60,
    favorite: true,
    origins: ["Mexico"],
    stars: 4.2,
    imageUrl: "food-4.jpg",
    tags: ["Fast Food", "Mexican"],
  },
  {
    id: "5",
    name: "Pasta Alfredo",
    cookTime: "15-25",
    price: 120,
    favorite: false,
    origins: ["Italy"],
    stars: 4.3,
    imageUrl: "food-5.jpg",
    tags: ["Italian", "Pasta"],
  },
  {
    id: "6",
    name: "Caesar Salad",
    cookTime: "5-10",
    price: 700,
    favorite: true,
    origins: ["US"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["Healthy", "Salad"],
  },
  {
    id: "7",
    name: "Ramen Noodles",
    cookTime: "10-20",
    price: 90,
    favorite: false,
    origins: ["Japan"],
    stars: 4.6,
    imageUrl: "food-7.jpg",
    tags: ["Soup", "Asian"],
  },
  {
    id: "8",
    name: "Fried Chicken",
    cookTime: "15-25",
    price: 110,
    favorite: true,
    origins: ["US", "Korea"],
    stars: 4.4,
    imageUrl: "food-8.jpg",
    tags: ["Fast Food", "Chicken"],
  },
  {
    id: "9",
    name: "Vegetable Stir Fry",
    cookTime: "10-15",
    price: 80,
    favorite: false,
    origins: ["China"],
    stars: 4.1,
    imageUrl: "food-9.jpg",
    tags: ["Vegetarian", "Asian"],
  },
  {
    id: "10",
    name: "Ice Cream Sundae",
    cookTime: "5-10",
    price: 500,
    favorite: true,
    origins: ["US"],
    stars: 4.8,
    imageUrl: "food-101.jpg",
    tags: ["Dessert", "Sweet"],
  },
];

const sample_tags = [
  { name: "All", count: 10 },
  { name: "Fast Food", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Dessert", count: 1 },
  { name: "Sweet", count: 1 },
  { name: "Burger", count: 1 },
  { name: "Chicken", count: 1 },
  { name: "Vegetarian", count: 1 },
  { name: "Asian", count: 2 },
  { name: "Mexican", count: 2 },
  { name: "Healthy", count: 2 },
  { name: "Soup", count: 1 },
];

const Sample_users = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    password: "password123",
    address: "123 Main St",
    isAdmin: false,
  },
  {
    name: "Jane Admin",
    email: "jane.admin@example.com",
    password: "admin123",
    address: "456 Admin St",
    isAdmin: true,
  },
];

module.exports = { Sample_users };